name: Vamp gateway agent
description: |
  (Experimental) Vamp Gateway Agent
version: 0.8.5-rancher1
category: clustering
maintainer: "BBVA Innovation Technologies <innotech@bbva.com>"
minimum_rancher_version: v0.59.0
license: 
