lb:
    ports:
        - ${public_port}:80
    tty: true
    image: rancher/load-balancer-service
    links:
        - application
    stdin_open: true
application:
    labels:
        io.rancher.container.pull_image: always
    restart: always
    image: ${application_image}
    expose:
        - "80"
    links:
        - mysql
        - mongo
        - redis
    volumes:
        - /data/www/${application_name}/logs/nginx:/var/log/nginx
        - /data/www/${application_name}/storage:/var/www/laravel/storage
mysql:
    restart: always
    image: mysql
    expose:
        - "3306"
    environment:
        MYSQL_DATABASE: ${mysql_database}
        MYSQL_USER: ${mysql_user}
        MYSQL_PASSWORD: ${mysql_password}
        MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    volumes:
        - /data/www/${application_name}/mysql:/var/lib/mysql
mongo:
    restart: always
    image: mongo
    expose:
        - "27017"
    volumes:
        - /data/www/${application_name}/data:/data
        - /data/www/${application_name}/logs/mongodb:/var/log/mongodb
redis:
    restart: always
    image: redis
    expose:
        - "6379"
    volumes:
        - /data/www/${application_name}/data:/data
